name: Spell Checker

on:
  pull_request:
    branches: ["main", "develop"]

permissions:
  contents: write
  pull-requests: write
  actions: read

jobs:
  spelling:
    name: Check Spelling
    runs-on: ubuntu-latest
    concurrency:
      group: spelling-${{ github.event.pull_request.number || github.ref }}
      # note: If you use only_check_changed_files, you do not want cancel-in-progress
      cancel-in-progress: true
    steps:
      - name: check-spelling
        id: spelling
        uses: check-spelling/check-spelling@v0.0.24
        with:
          suppress_push_for_open_pull_request: 1
          checkout: true
          check_file_names: 1
          spell_check_this: check-spelling/spell-check-this@v0.0.24
          post_comment: 1
          use_magic_file: 1
          extra_dictionary_limit: 10
          quit_without_error: 0
          extra_dictionaries: |
            cspell:software-terms/dict/softwareTerms.txt
            cspell:python/src/python/python-lib.txt
            cspell:npm/dict/npm.txt
            cspell:python/src/python/python.txt
            cspell:python/src/common/extra.txt
            cspell:typescript/dict/typescript.txt
            cspell:html/dict/html.txt
            cspell:filetypes/filetypes.txt
            cspell:php/dict/php.txt
            cspell:fullstack/dict/fullstack.txt
            cspell:aws/aws.txt
            cspell:node/dict/node.txt
            cspell:r/src/r.txt
            cspell:golang/dict/go.txt
            cspell:k8s/dict/k8s.txt
            cspell:dotnet/dict/dotnet.txt
            cspell:django/requirements.txt
            cspell:docker/src/docker-words.txt
